image: node:10.15.1

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - cd app && zip -r ../pharmacy-app.zip *
        artifacts:
          - pharmacy-app.zip
    - step:
        name: Deploy
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "AWS_DEFAULT_REGION"
              S3_BUCKET: "dbsmedapp"
              LOCAL_PATH: "dist"
              ACL: "public-read"
              CACHE_CONTROL: "max-age=3600"
              EXPIRES: "2018-10-01T00:00:00+00:00"
              DELETE_FLAG: "true"
              EXTRA_ARGS: "--follow-symlinks"