image: atlassian/default-image:2


pipelines:
  default:
    - step:
        name: Build
        script:
          - cd app && zip -r ../pharmacy-app.zip *
        artifacts:
          - pharmacy-app.zip

    - step:
        name: Upload to S3
        services:
          - docker
        script:
          # Test upload
          - pipe: atlassian/aws-code-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              COMMAND: 'upload'
              APPLICATION_NAME: ${APPLICATION_NAME}
              ZIP_FILE: 'pharmacy-app.zip'

    - step:
        name: Deploy with CodeDeploy
        services:
          - docker
        script:
          # Test upload
          - pipe: atlassian/aws-code-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              COMMAND: 'deploy'
              APPLICATION_NAME: ${APPLICATION_NAME}
              DEPLOYMENT_GROUP: ${DEPLOYMENT_GROUP}
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
              WAIT: 'true'