########## Spring Properties ##########
server:
  servlet:
    context-path: /pharmacy-app
  port: 8080
spring:
  application:
    name: pharmacy-app
  datasource:    
    url: jdbc:mysql://database-1.coe01ji2vat6.ap-south-1.rds.amazonaws.com:3306/DBS
    username: XXXXX
    password: XXXXX
    driver-class: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: XXXXX
    password: XXXXX
    properties:      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout=: 5000
          writetimeout:  5000
          starttls:
            enable: true
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

########## Application Properties ##########
pharmacyapp:
  client-id: pharma-app-client
  client-secret: pharma-app-secret
