########## Spring Properties ##########
server:
  servlet:
    context-path: /pharmacy-app
  port: 8080
spring:
  application:
    name: pharmacy-app
  datasource:    
    url: jdbc:mysql://database-1.coe01ji2vat6.ap-south-1.rds.amazonaws.com:3306/DBS
    username: admin
    password: hack2hire
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

########## Application Properties ##########
pharmacyapp:
  client-id: pharma-app-client
  client-secret: pharma-app-secret
